name: Release
run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
      && format('Release {0} @{1}', github.ref_name, github.sha)
      || '' }}

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      module:
        description: 'Choose module to deploy'
        required: true
        type: choice
        options:
          - "plusminus-configs"
          - "plusminus-parent"

jobs:
  release:
    uses: plusminus-software/plusminus-workflows/.github/workflows/maven-central-release.yml@main
    with:
      java-version: '8'
      module: ${{ github.event.inputs.module }}
    secrets: inherit